# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
pimcore:
    security:
        # the encoder factory as defined in services.yml
        encoder_factories:
            Pimcore\Model\Object\Customer: cmf.authentication.user_password_encoder_factory

security:
    providers:
        cmf:
          id: cmf.authentication.user_provider

    firewalls:
        main:
            anonymous: ~
            provider: cmf
            form_login:
                login_path: app_auth_login
                check_path: app_auth_login
                default_target_path: app_auth_secure
            logout:
                path: app_auth_logout
                target: app_auth_login
