services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    CustomerManagementFrameworkBundle\Targeting\ActionHandler\TrackSegment: ~
    CustomerManagementFrameworkBundle\Targeting\ActionHandler\TrackElementSegments: ~

