pimcore:
    custom_report:
        adapters:
            termSegmentBuilder: cmf.custom_report.adapter.term_segment_builder

    targeting:
        conditions:
            cmf_segment_tracked: CustomerManagementFrameworkBundle\Targeting\Condition\SegmentTracked
        action_handlers:
            cmf_track_segment: CustomerManagementFrameworkBundle\Targeting\ActionHandler\TrackSegment

monolog:
    channels: ['cmf']
